#!/usr/bin/env python3
"""
Generate mzip_amalgamated.hpp from source files.

Usage:
    python amalgamate.py > mzip_amalgamated.hpp

The generated header follows the stb pattern:
    #include <zstd.h>  // Required first
    #define MZIP_IMPLEMENTATION
    #include "mzip_amalgamated.hpp"
"""

import re
from pathlib import Path

# Order matters: dependencies before dependents
INCLUDE_ORDER = [
    # C dependencies (wrapped for C++)
    ("libsais.h", "c_header"),
    ("libsais.c", "c_impl"),
    # BWT stack
    ("bwt_compress_v8.hpp", "hpp"),
    ("bwt_compress_v5.hpp", "hpp"),
    ("bwt_compress_v9.hpp", "hpp"),
    # Utilities
    ("tieredcompress.hpp", "hpp"),
    # PPMd var.H backstop (LZMA-SDK Ppmd7, public domain).
    # Headers first, in strict dependency order (each self-manages its own
    # extern "C" via EXTERN_C_BEGIN/END and carries a ZIP7_* include guard);
    # then the C sources (wrapped in extern "C"); then the C++ wrapper.
    # ALL of this must precede mzip.hpp, which calls ppmdbk::compress/decompress.
    ("ppmd/Compiler.h", "ppmd_header"),
    ("ppmd/7zTypes.h", "ppmd_header"),
    ("ppmd/CpuArch.h", "ppmd_header"),
    ("ppmd/Ppmd.h", "ppmd_header"),
    ("ppmd/Ppmd7.h", "ppmd_header"),
    ("ppmd/Ppmd7.c", "ppmd_impl"),
    ("ppmd/Ppmd7Enc.c", "ppmd_impl"),
    ("ppmd/Ppmd7Dec.c", "ppmd_impl"),
    ("ppmd_backend.hpp", "hpp"),
    # Main library
    ("mzip.hpp", "hpp"),
]

HEADER_COMMENT = '''/*
 * mzip_amalgamated.hpp - Single-header adaptive compression library
 *
 * QUICK START:
 *   // In ONE .cpp file:
 *   #include <zstd.h>                    // Required: zstd header
 *   #define MZIP_IMPLEMENTATION
 *   #include "mzip_amalgamated.hpp"
 *
 *   // In other files, just:
 *   #include "mzip_amalgamated.hpp"
 *
 * USAGE:
 *   auto compressed = mzip::compress(data, size);
 *   auto decompressed = mzip::decompress(compressed.data(), compressed.size());
 *
 * REQUIREMENTS:
 *   - C++17 or later
 *   - zstd library (link with -lzstd)
 *
 * LICENSE:
 *   mzip: MIT
 *   libsais: Apache 2.0 (bundled, see license notice below)
 *
 * Generated by amalgamate.py - do not edit directly.
 */

'''

LIBSAIS_LICENSE = '''
// =============================================================================
// libsais - Suffix Array / BWT construction (Apache 2.0)
// Copyright (c) 2021-2024 Ilya Grebnov <ilya.grebnov@gmail.com>
// https://github.com/IlyaGrebnov/libsais
// =============================================================================

'''

PPMD_LICENSE = '''
// =============================================================================
// PPMd var.H (Ppmd7 / PPMdH) codec - PUBLIC DOMAIN (LZMA-SDK)
//   Ppmd7*.c/.h : 2023 : Igor Pavlov : Public domain
//   based on PPMd var.H (2001) : Dmitry Shkarin : Public domain
// The LZMA-SDK support headers (7zTypes.h, CpuArch.h, Compiler.h) are also
// public domain.  Local #include "..." lines are stripped and the headers are
// inlined above in dependency order; each retains its ZIP7_* include guard so
// no symbol is defined twice.
// =============================================================================

'''

def process_c_header(content):
    """Process libsais.h - keep as extern C declarations."""
    # Remove include guards (we'll use pragma once)
    content = re.sub(r'#ifndef\s+LIBSAIS_H\s*\n#define\s+LIBSAIS_H\s*\n', '', content)
    content = re.sub(r'#endif\s*/\*\s*LIBSAIS_H\s*\*/', '', content)
    content = re.sub(r'#pragma once\s*', '', content)
    return content

def process_c_impl(content):
    """Process libsais.c - include directly with extern "C" wrapper."""
    # Remove include of libsais.h (already included)
    content = re.sub(r'#include\s+"libsais\.h"\s*\n?', '', content)
    # Return as-is - the extern "C" declarations from the header are sufficient
    return content

def strip_local_includes(content):
    """Remove every local (quoted) #include line; keep system <...> includes.

    Used for the bundled LZMA-SDK ppmd sources/headers: each internal
    #include "Precomp.h" / "Ppmd7.h" / "CpuArch.h" ... is inlined elsewhere in
    this file, so the quoted include must go while <string.h>/<stdint.h> stay.
    """
    return re.sub(r'^[ \t]*#[ \t]*include[ \t]+"[^"]*"[ \t]*\r?\n?', '',
                  content, flags=re.MULTILINE)

def process_ppmd_header(content):
    """Process an LZMA-SDK ppmd header.

    Keep its ZIP7_* include guard (idempotent, prevents double-definition) and
    its own EXTERN_C_BEGIN/END (self-managed C linkage); strip only the local
    quoted includes, which are inlined ahead of it in dependency order.
    """
    return strip_local_includes(content)

def process_ppmd_impl(content):
    """Process an LZMA-SDK ppmd .c source - strip local includes; keep <...>.

    The caller wraps the body in extern "C" so definitions get C linkage that
    matches the extern "C" declarations from the inlined Ppmd7.h.
    """
    return strip_local_includes(content)

def process_hpp(content, filename):
    """Process C++ header - remove local includes and pragma once."""
    # Remove pragma once
    content = re.sub(r'#pragma once\s*', '', content)

    # Remove local includes that will be concatenated.
    # ppmd_backend.hpp: strip mzip.hpp's include of it AND its own
    # extern "C" { #include "ppmd/Ppmd7.h" } (Ppmd7.h is inlined above).
    local_headers = [
        'libsais.h', 'bwt_compress_v5.hpp', 'bwt_compress_v8.hpp',
        'bwt_compress_v9.hpp', 'tieredcompress.hpp',
        'ppmd_backend.hpp', 'Ppmd7.h',
    ]
    for h in local_headers:
        # Remove the extern "C" { #include "..." } wrapper form FIRST, so the
        # whole block goes (otherwise the bare-include sub would leave an empty
        # extern "C" {}).
        content = re.sub(rf'extern\s+"C"\s*\{{\s*#include\s+"[^"]*{re.escape(h)}"\s*\}}\s*\n?', '', content)
        content = re.sub(rf'#include\s+"[^"]*{re.escape(h)}"\s*\n?', '', content)

    # libsais functions are exposed via extern "C" - no namespace needed

    return content

def read_file(filename):
    """Read file content."""
    path = Path(filename)
    if not path.exists():
        raise FileNotFoundError(f"Missing: {filename}")
    return path.read_text(encoding='utf-8', errors='replace')

def generate_amalgamation():
    """Generate the amalgamated header."""
    output = []

    # Header comment and guards
    output.append(HEADER_COMMENT)
    output.append('#ifndef MZIP_AMALGAMATED_HPP\n')
    output.append('#define MZIP_AMALGAMATED_HPP\n\n')

    # Standard includes needed by all components
    output.append('''// Standard library includes
#include <cstdint>
#include <cstring>
#include <vector>
#include <algorithm>
#include <numeric>
#include <string>
#include <array>
#include <functional>
#include <queue>
#include <limits>
#include <cmath>
#include <utility>

// zstd must be included before this header
#ifndef ZSTD_H_235446
#error "Please include <zstd.h> before mzip_amalgamated.hpp"
#endif

''')

    # End of header-only section
    output.append('#endif // MZIP_AMALGAMATED_HPP\n\n')

    # Implementation section
    output.append('// =============================================================================\n')
    output.append('// IMPLEMENTATION - Define MZIP_IMPLEMENTATION in exactly one source file\n')
    output.append('// =============================================================================\n\n')
    output.append('#ifdef MZIP_IMPLEMENTATION\n')
    output.append('#ifndef MZIP_IMPLEMENTATION_INCLUDED\n')
    output.append('#define MZIP_IMPLEMENTATION_INCLUDED\n\n')

    # Process each file
    for filename, filetype in INCLUDE_ORDER:
        output.append(f'// =============================================================================\n')
        output.append(f'// {filename}\n')
        output.append(f'// =============================================================================\n\n')

        if filename == 'libsais.h':
            output.append(LIBSAIS_LICENSE)
        if filename == 'ppmd/Compiler.h':
            output.append(PPMD_LICENSE)

        content = read_file(filename)

        if filetype == 'c_header':
            content = process_c_header(content)
            # Wrap in extern "C" for C++ compatibility
            output.append('extern "C" {\n')
            output.append(content)
            output.append('\n} // extern "C"\n\n')
        elif filetype == 'c_impl':
            content = process_c_impl(content)
            # Wrap C implementation in extern "C" for C++ compatibility
            output.append('extern "C" {\n')
            output.append(content)
            output.append('\n} // extern "C"\n\n')
        elif filetype == 'ppmd_header':
            # LZMA-SDK header: NO outer extern "C" (it self-manages via
            # EXTERN_C_BEGIN/END); keep its guard; strip local includes only.
            content = process_ppmd_header(content)
            output.append(content)
        elif filetype == 'ppmd_impl':
            # LZMA-SDK .c source compiled as C++: wrap in extern "C".
            content = process_ppmd_impl(content)
            output.append('extern "C" {\n')
            output.append(content)
            output.append('\n} // extern "C"\n\n')
        else:  # hpp
            content = process_hpp(content, filename)
            output.append(content)

        output.append('\n')

    # Close implementation guard
    output.append('#endif // MZIP_IMPLEMENTATION_INCLUDED\n')
    output.append('#endif // MZIP_IMPLEMENTATION\n')

    return ''.join(output)

if __name__ == '__main__':
    import sys
    # Force UTF-8 output on Windows
    sys.stdout.reconfigure(encoding='utf-8')
    result = generate_amalgamation()
    # Replace Unicode arrows with ASCII for portability
    result = result.replace('\u2192', '->')  # → -> ->
    print(result)
