# Makefile generated by generator

CC      := gcc
CXX     := g++
CFLAGS  := -Wall -Wextra -O2
CXXFLAGS := -Wall -Wextra -O2 -std=c++17
LDFLAGS := -lpthread
PREFIX  := /usr/local
SRCDIR  := src
OBJDIR  := obj
BINDIR  := bin

# Object files for module 0
OBJS_0 := $(OBJDIR)/file0_0.o $(OBJDIR)/file0_1.o $(OBJDIR)/file0_2.o $(OBJDIR)/file0_3.o 

$(OBJDIR)/file0_%.o: $(SRCDIR)/file0_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: build-1
build-1:
	@echo "Running build 1..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-1 $(SRCDIR)/main-1.cpp $(LDFLAGS)

.PHONY: clean-2
clean-2: lint-1
	@echo "Running clean 2..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-2

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-4
install-4:
	@echo "Running install 4..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-4 $(SRCDIR)/main-4.cpp $(LDFLAGS)

.PHONY: run-5
run-5:
	@echo "Running run 5..."
	@echo "Done with run 5"

.PHONY: dist-6
dist-6: docs-5
	@echo "Running dist 6..."
	@echo "Done with dist 6"

.PHONY: docs-7
docs-7: dist-6
	@echo "Running docs 7..."
	@echo "Done with docs 7"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-9
check-9: test-8
	@echo "Running check 9..."
	@echo "Done with check 9"

.PHONY: all-10
all-10: docs-9
	@echo "Running all 10..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-10 $(SRCDIR)/main-10.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 12
OBJS_12 := $(OBJDIR)/file12_0.o $(OBJDIR)/file12_1.o $(OBJDIR)/file12_2.o $(OBJDIR)/file12_3.o $(OBJDIR)/file12_4.o $(OBJDIR)/file12_5.o 

$(OBJDIR)/file12_%.o: $(SRCDIR)/file12_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 13
OBJS_13 := $(OBJDIR)/file13_0.o $(OBJDIR)/file13_1.o $(OBJDIR)/file13_2.o $(OBJDIR)/file13_3.o $(OBJDIR)/file13_4.o 

$(OBJDIR)/file13_%.o: $(SRCDIR)/file13_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 18
OBJS_18 := $(OBJDIR)/file18_0.o $(OBJDIR)/file18_1.o $(OBJDIR)/file18_2.o $(OBJDIR)/file18_3.o 

$(OBJDIR)/file18_%.o: $(SRCDIR)/file18_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-20
all-20:
	@echo "Running all 20..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-20 $(SRCDIR)/main-20.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-23
test-23:
	@echo "Running test 23..."
	./$(BINDIR)/test-23

.PHONY: install-24
install-24:
	@echo "Running install 24..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-24 $(SRCDIR)/main-24.cpp $(LDFLAGS)

.PHONY: run-25
run-25: test-24
	@echo "Running run 25..."
	@echo "Done with run 25"

.PHONY: dist-26
dist-26: build-25
	@echo "Running dist 26..."
	@echo "Done with dist 26"

# Object files for module 27
OBJS_27 := $(OBJDIR)/file27_0.o $(OBJDIR)/file27_1.o $(OBJDIR)/file27_2.o $(OBJDIR)/file27_3.o $(OBJDIR)/file27_4.o $(OBJDIR)/file27_5.o 

$(OBJDIR)/file27_%.o: $(SRCDIR)/file27_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-29
check-29:
	@echo "Running check 29..."
	@echo "Done with check 29"

.PHONY: all-30
all-30:
	@echo "Running all 30..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-30 $(SRCDIR)/main-30.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 32
OBJS_32 := $(OBJDIR)/file32_0.o $(OBJDIR)/file32_1.o $(OBJDIR)/file32_2.o 

$(OBJDIR)/file32_%.o: $(SRCDIR)/file32_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 34
OBJS_34 := $(OBJDIR)/file34_0.o $(OBJDIR)/file34_1.o $(OBJDIR)/file34_2.o $(OBJDIR)/file34_3.o 

$(OBJDIR)/file34_%.o: $(SRCDIR)/file34_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-35
run-35: build-34
	@echo "Running run 35..."
	@echo "Done with run 35"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-37
docs-37: docs-36
	@echo "Running docs 37..."
	@echo "Done with docs 37"

.PHONY: lint-38
lint-38: build-37
	@echo "Running lint 38..."
	@echo "Done with lint 38"

.PHONY: check-39
check-39: run-38
	@echo "Running check 39..."
	@echo "Done with check 39"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-41
build-41:
	@echo "Running build 41..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-41 $(SRCDIR)/main-41.cpp $(LDFLAGS)

.PHONY: clean-42
clean-42: all-41
	@echo "Running clean 42..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-42

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-44
install-44: build-43
	@echo "Running install 44..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-44 $(SRCDIR)/main-44.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-47
docs-47: dist-46
	@echo "Running docs 47..."
	@echo "Done with docs 47"

.PHONY: lint-48
lint-48: run-47
	@echo "Running lint 48..."
	@echo "Done with lint 48"

# Object files for module 49
OBJS_49 := $(OBJDIR)/file49_0.o $(OBJDIR)/file49_1.o $(OBJDIR)/file49_2.o $(OBJDIR)/file49_3.o 

$(OBJDIR)/file49_%.o: $(SRCDIR)/file49_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all-50
all-50:
	@echo "Running all 50..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-50 $(SRCDIR)/main-50.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-52
clean-52:
	@echo "Running clean 52..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-52

.PHONY: test-53
test-53:
	@echo "Running test 53..."
	./$(BINDIR)/test-53

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-55
run-55: check-54
	@echo "Running run 55..."
	@echo "Done with run 55"

.PHONY: dist-56
dist-56:
	@echo "Running dist 56..."
	@echo "Done with dist 56"

.PHONY: docs-57
docs-57:
	@echo "Running docs 57..."
	@echo "Done with docs 57"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 59
OBJS_59 := $(OBJDIR)/file59_0.o $(OBJDIR)/file59_1.o $(OBJDIR)/file59_2.o $(OBJDIR)/file59_3.o $(OBJDIR)/file59_4.o 

$(OBJDIR)/file59_%.o: $(SRCDIR)/file59_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all-60
all-60: all-59
	@echo "Running all 60..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-60 $(SRCDIR)/main-60.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-62
clean-62:
	@echo "Running clean 62..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-62

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 64
OBJS_64 := $(OBJDIR)/file64_0.o $(OBJDIR)/file64_1.o $(OBJDIR)/file64_2.o $(OBJDIR)/file64_3.o $(OBJDIR)/file64_4.o 

$(OBJDIR)/file64_%.o: $(SRCDIR)/file64_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-65
run-65:
	@echo "Running run 65..."
	@echo "Done with run 65"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-67
docs-67: check-66
	@echo "Running docs 67..."
	@echo "Done with docs 67"

# Object files for module 68
OBJS_68 := $(OBJDIR)/file68_0.o $(OBJDIR)/file68_1.o $(OBJDIR)/file68_2.o $(OBJDIR)/file68_3.o $(OBJDIR)/file68_4.o 

$(OBJDIR)/file68_%.o: $(SRCDIR)/file68_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: check-69
check-69:
	@echo "Running check 69..."
	@echo "Done with check 69"

.PHONY: all-70
all-70: all-69
	@echo "Running all 70..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-70 $(SRCDIR)/main-70.cpp $(LDFLAGS)

.PHONY: build-71
build-71: clean-70
	@echo "Running build 71..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-71 $(SRCDIR)/main-71.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 73
OBJS_73 := $(OBJDIR)/file73_0.o $(OBJDIR)/file73_1.o $(OBJDIR)/file73_2.o $(OBJDIR)/file73_3.o 

$(OBJDIR)/file73_%.o: $(SRCDIR)/file73_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: install-74
install-74:
	@echo "Running install 74..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-74 $(SRCDIR)/main-74.cpp $(LDFLAGS)

.PHONY: run-75
run-75: install-74
	@echo "Running run 75..."
	@echo "Done with run 75"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 78
OBJS_78 := $(OBJDIR)/file78_0.o $(OBJDIR)/file78_1.o $(OBJDIR)/file78_2.o $(OBJDIR)/file78_3.o $(OBJDIR)/file78_4.o 

$(OBJDIR)/file78_%.o: $(SRCDIR)/file78_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 80
OBJS_80 := $(OBJDIR)/file80_0.o $(OBJDIR)/file80_1.o $(OBJDIR)/file80_2.o 

$(OBJDIR)/file80_%.o: $(SRCDIR)/file80_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 81
OBJS_81 := $(OBJDIR)/file81_0.o $(OBJDIR)/file81_1.o $(OBJDIR)/file81_2.o $(OBJDIR)/file81_3.o 

$(OBJDIR)/file81_%.o: $(SRCDIR)/file81_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-83
test-83:
	@echo "Running test 83..."
	./$(BINDIR)/test-83

.PHONY: install-84
install-84:
	@echo "Running install 84..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-84 $(SRCDIR)/main-84.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-86
dist-86: docs-85
	@echo "Running dist 86..."
	@echo "Done with dist 86"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-89
check-89: docs-88
	@echo "Running check 89..."
	@echo "Done with check 89"

.PHONY: all-90
all-90: build-89
	@echo "Running all 90..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-90 $(SRCDIR)/main-90.cpp $(LDFLAGS)

.PHONY: build-91
build-91: dist-90
	@echo "Running build 91..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-91 $(SRCDIR)/main-91.cpp $(LDFLAGS)

# Object files for module 92
OBJS_92 := $(OBJDIR)/file92_0.o $(OBJDIR)/file92_1.o $(OBJDIR)/file92_2.o $(OBJDIR)/file92_3.o $(OBJDIR)/file92_4.o $(OBJDIR)/file92_5.o 

$(OBJDIR)/file92_%.o: $(SRCDIR)/file92_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-93
test-93:
	@echo "Running test 93..."
	./$(BINDIR)/test-93

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: lint-98
lint-98:
	@echo "Running lint 98..."
	@echo "Done with lint 98"

.PHONY: check-99
check-99: install-98
	@echo "Running check 99..."
	@echo "Done with check 99"

# Object files for module 100
OBJS_100 := $(OBJDIR)/file100_0.o $(OBJDIR)/file100_1.o $(OBJDIR)/file100_2.o $(OBJDIR)/file100_3.o 

$(OBJDIR)/file100_%.o: $(SRCDIR)/file100_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 102
OBJS_102 := $(OBJDIR)/file102_0.o $(OBJDIR)/file102_1.o $(OBJDIR)/file102_2.o $(OBJDIR)/file102_3.o 

$(OBJDIR)/file102_%.o: $(SRCDIR)/file102_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 104
OBJS_104 := $(OBJDIR)/file104_0.o $(OBJDIR)/file104_1.o $(OBJDIR)/file104_2.o $(OBJDIR)/file104_3.o $(OBJDIR)/file104_4.o 

$(OBJDIR)/file104_%.o: $(SRCDIR)/file104_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 106
OBJS_106 := $(OBJDIR)/file106_0.o $(OBJDIR)/file106_1.o $(OBJDIR)/file106_2.o 

$(OBJDIR)/file106_%.o: $(SRCDIR)/file106_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-107
docs-107:
	@echo "Running docs 107..."
	@echo "Done with docs 107"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-109
check-109: run-108
	@echo "Running check 109..."
	@echo "Done with check 109"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-111
build-111:
	@echo "Running build 111..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-111 $(SRCDIR)/main-111.cpp $(LDFLAGS)

# Object files for module 112
OBJS_112 := $(OBJDIR)/file112_0.o $(OBJDIR)/file112_1.o $(OBJDIR)/file112_2.o $(OBJDIR)/file112_3.o 

$(OBJDIR)/file112_%.o: $(SRCDIR)/file112_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-113
test-113: build-112
	@echo "Running test 113..."
	./$(BINDIR)/test-113

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 116
OBJS_116 := $(OBJDIR)/file116_0.o $(OBJDIR)/file116_1.o $(OBJDIR)/file116_2.o $(OBJDIR)/file116_3.o 

$(OBJDIR)/file116_%.o: $(SRCDIR)/file116_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-119
check-119: run-118
	@echo "Running check 119..."
	@echo "Done with check 119"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-121
build-121: build-120
	@echo "Running build 121..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-121 $(SRCDIR)/main-121.cpp $(LDFLAGS)

.PHONY: clean-122
clean-122:
	@echo "Running clean 122..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-122

# Object files for module 123
OBJS_123 := $(OBJDIR)/file123_0.o $(OBJDIR)/file123_1.o $(OBJDIR)/file123_2.o 

$(OBJDIR)/file123_%.o: $(SRCDIR)/file123_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-125
run-125: test-124
	@echo "Running run 125..."
	@echo "Done with run 125"

.PHONY: dist-126
dist-126:
	@echo "Running dist 126..."
	@echo "Done with dist 126"

.PHONY: docs-127
docs-127: install-126
	@echo "Running docs 127..."
	@echo "Done with docs 127"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 132
OBJS_132 := $(OBJDIR)/file132_0.o $(OBJDIR)/file132_1.o $(OBJDIR)/file132_2.o $(OBJDIR)/file132_3.o $(OBJDIR)/file132_4.o $(OBJDIR)/file132_5.o 

$(OBJDIR)/file132_%.o: $(SRCDIR)/file132_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 136
OBJS_136 := $(OBJDIR)/file136_0.o $(OBJDIR)/file136_1.o $(OBJDIR)/file136_2.o $(OBJDIR)/file136_3.o $(OBJDIR)/file136_4.o 

$(OBJDIR)/file136_%.o: $(SRCDIR)/file136_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-137
docs-137:
	@echo "Running docs 137..."
	@echo "Done with docs 137"

# Object files for module 138
OBJS_138 := $(OBJDIR)/file138_0.o $(OBJDIR)/file138_1.o $(OBJDIR)/file138_2.o $(OBJDIR)/file138_3.o 

$(OBJDIR)/file138_%.o: $(SRCDIR)/file138_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 140
OBJS_140 := $(OBJDIR)/file140_0.o $(OBJDIR)/file140_1.o $(OBJDIR)/file140_2.o $(OBJDIR)/file140_3.o $(OBJDIR)/file140_4.o $(OBJDIR)/file140_5.o 

$(OBJDIR)/file140_%.o: $(SRCDIR)/file140_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 141
OBJS_141 := $(OBJDIR)/file141_0.o $(OBJDIR)/file141_1.o $(OBJDIR)/file141_2.o $(OBJDIR)/file141_3.o $(OBJDIR)/file141_4.o $(OBJDIR)/file141_5.o 

$(OBJDIR)/file141_%.o: $(SRCDIR)/file141_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-143
test-143:
	@echo "Running test 143..."
	./$(BINDIR)/test-143

.PHONY: install-144
install-144: test-143
	@echo "Running install 144..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-144 $(SRCDIR)/main-144.cpp $(LDFLAGS)

# Object files for module 145
OBJS_145 := $(OBJDIR)/file145_0.o $(OBJDIR)/file145_1.o $(OBJDIR)/file145_2.o $(OBJDIR)/file145_3.o 

$(OBJDIR)/file145_%.o: $(SRCDIR)/file145_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-147
docs-147:
	@echo "Running docs 147..."
	@echo "Done with docs 147"

# Object files for module 148
OBJS_148 := $(OBJDIR)/file148_0.o $(OBJDIR)/file148_1.o $(OBJDIR)/file148_2.o $(OBJDIR)/file148_3.o $(OBJDIR)/file148_4.o 

$(OBJDIR)/file148_%.o: $(SRCDIR)/file148_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: check-149
check-149: docs-148
	@echo "Running check 149..."
	@echo "Done with check 149"

# Object files for module 150
OBJS_150 := $(OBJDIR)/file150_0.o $(OBJDIR)/file150_1.o $(OBJDIR)/file150_2.o $(OBJDIR)/file150_3.o $(OBJDIR)/file150_4.o $(OBJDIR)/file150_5.o 

$(OBJDIR)/file150_%.o: $(SRCDIR)/file150_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-153
test-153: all-152
	@echo "Running test 153..."
	./$(BINDIR)/test-153

# Object files for module 154
OBJS_154 := $(OBJDIR)/file154_0.o $(OBJDIR)/file154_1.o $(OBJDIR)/file154_2.o $(OBJDIR)/file154_3.o $(OBJDIR)/file154_4.o 

$(OBJDIR)/file154_%.o: $(SRCDIR)/file154_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 157
OBJS_157 := $(OBJDIR)/file157_0.o $(OBJDIR)/file157_1.o $(OBJDIR)/file157_2.o $(OBJDIR)/file157_3.o $(OBJDIR)/file157_4.o $(OBJDIR)/file157_5.o 

$(OBJDIR)/file157_%.o: $(SRCDIR)/file157_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-161
build-161: all-160
	@echo "Running build 161..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-161 $(SRCDIR)/main-161.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 164
OBJS_164 := $(OBJDIR)/file164_0.o $(OBJDIR)/file164_1.o $(OBJDIR)/file164_2.o $(OBJDIR)/file164_3.o $(OBJDIR)/file164_4.o 

$(OBJDIR)/file164_%.o: $(SRCDIR)/file164_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-165
run-165:
	@echo "Running run 165..."
	@echo "Done with run 165"

.PHONY: dist-166
dist-166:
	@echo "Running dist 166..."
	@echo "Done with dist 166"

.PHONY: docs-167
docs-167:
	@echo "Running docs 167..."
	@echo "Done with docs 167"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-170
all-170:
	@echo "Running all 170..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-170 $(SRCDIR)/main-170.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-173
test-173: install-172
	@echo "Running test 173..."
	./$(BINDIR)/test-173

.PHONY: install-174
install-174:
	@echo "Running install 174..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-174 $(SRCDIR)/main-174.cpp $(LDFLAGS)

# Object files for module 175
OBJS_175 := $(OBJDIR)/file175_0.o $(OBJDIR)/file175_1.o $(OBJDIR)/file175_2.o $(OBJDIR)/file175_3.o 

$(OBJDIR)/file175_%.o: $(SRCDIR)/file175_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 176
OBJS_176 := $(OBJDIR)/file176_0.o $(OBJDIR)/file176_1.o $(OBJDIR)/file176_2.o 

$(OBJDIR)/file176_%.o: $(SRCDIR)/file176_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-177
docs-177: all-176
	@echo "Running docs 177..."
	@echo "Done with docs 177"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-180
all-180:
	@echo "Running all 180..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-180 $(SRCDIR)/main-180.cpp $(LDFLAGS)

# Object files for module 181
OBJS_181 := $(OBJDIR)/file181_0.o $(OBJDIR)/file181_1.o $(OBJDIR)/file181_2.o $(OBJDIR)/file181_3.o $(OBJDIR)/file181_4.o 

$(OBJDIR)/file181_%.o: $(SRCDIR)/file181_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 182
OBJS_182 := $(OBJDIR)/file182_0.o $(OBJDIR)/file182_1.o $(OBJDIR)/file182_2.o $(OBJDIR)/file182_3.o 

$(OBJDIR)/file182_%.o: $(SRCDIR)/file182_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-184
install-184: run-183
	@echo "Running install 184..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-184 $(SRCDIR)/main-184.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-186
dist-186:
	@echo "Running dist 186..."
	@echo "Done with dist 186"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 190
OBJS_190 := $(OBJDIR)/file190_0.o $(OBJDIR)/file190_1.o $(OBJDIR)/file190_2.o 

$(OBJDIR)/file190_%.o: $(SRCDIR)/file190_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 192
OBJS_192 := $(OBJDIR)/file192_0.o $(OBJDIR)/file192_1.o $(OBJDIR)/file192_2.o $(OBJDIR)/file192_3.o 

$(OBJDIR)/file192_%.o: $(SRCDIR)/file192_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-193
test-193: dist-192
	@echo "Running test 193..."
	./$(BINDIR)/test-193

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-196
dist-196:
	@echo "Running dist 196..."
	@echo "Done with dist 196"

# Object files for module 197
OBJS_197 := $(OBJDIR)/file197_0.o $(OBJDIR)/file197_1.o $(OBJDIR)/file197_2.o $(OBJDIR)/file197_3.o $(OBJDIR)/file197_4.o $(OBJDIR)/file197_5.o 

$(OBJDIR)/file197_%.o: $(SRCDIR)/file197_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-199
check-199: dist-198
	@echo "Running check 199..."
	@echo "Done with check 199"

# Object files for module 200
OBJS_200 := $(OBJDIR)/file200_0.o $(OBJDIR)/file200_1.o $(OBJDIR)/file200_2.o 

$(OBJDIR)/file200_%.o: $(SRCDIR)/file200_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 201
OBJS_201 := $(OBJDIR)/file201_0.o $(OBJDIR)/file201_1.o $(OBJDIR)/file201_2.o $(OBJDIR)/file201_3.o $(OBJDIR)/file201_4.o $(OBJDIR)/file201_5.o 

$(OBJDIR)/file201_%.o: $(SRCDIR)/file201_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-203
test-203:
	@echo "Running test 203..."
	./$(BINDIR)/test-203

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 205
OBJS_205 := $(OBJDIR)/file205_0.o $(OBJDIR)/file205_1.o $(OBJDIR)/file205_2.o $(OBJDIR)/file205_3.o $(OBJDIR)/file205_4.o 

$(OBJDIR)/file205_%.o: $(SRCDIR)/file205_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-207
docs-207: lint-206
	@echo "Running docs 207..."
	@echo "Done with docs 207"

.PHONY: lint-208
lint-208:
	@echo "Running lint 208..."
	@echo "Done with lint 208"

# Object files for module 209
OBJS_209 := $(OBJDIR)/file209_0.o $(OBJDIR)/file209_1.o $(OBJDIR)/file209_2.o $(OBJDIR)/file209_3.o $(OBJDIR)/file209_4.o 

$(OBJDIR)/file209_%.o: $(SRCDIR)/file209_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all-210
all-210:
	@echo "Running all 210..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-210 $(SRCDIR)/main-210.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-212
clean-212: lint-211
	@echo "Running clean 212..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-212

.PHONY: test-213
test-213: all-212
	@echo "Running test 213..."
	./$(BINDIR)/test-213

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-215
run-215: clean-214
	@echo "Running run 215..."
	@echo "Done with run 215"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 217
OBJS_217 := $(OBJDIR)/file217_0.o $(OBJDIR)/file217_1.o $(OBJDIR)/file217_2.o $(OBJDIR)/file217_3.o 

$(OBJDIR)/file217_%.o: $(SRCDIR)/file217_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-219
check-219:
	@echo "Running check 219..."
	@echo "Done with check 219"

.PHONY: all-220
all-220: build-219
	@echo "Running all 220..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-220 $(SRCDIR)/main-220.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 222
OBJS_222 := $(OBJDIR)/file222_0.o $(OBJDIR)/file222_1.o $(OBJDIR)/file222_2.o $(OBJDIR)/file222_3.o $(OBJDIR)/file222_4.o $(OBJDIR)/file222_5.o 

$(OBJDIR)/file222_%.o: $(SRCDIR)/file222_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-225
run-225:
	@echo "Running run 225..."
	@echo "Done with run 225"

.PHONY: dist-226
dist-226:
	@echo "Running dist 226..."
	@echo "Done with dist 226"

# Object files for module 227
OBJS_227 := $(OBJDIR)/file227_0.o $(OBJDIR)/file227_1.o $(OBJDIR)/file227_2.o 

$(OBJDIR)/file227_%.o: $(SRCDIR)/file227_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: lint-228
lint-228: all-227
	@echo "Running lint 228..."
	@echo "Done with lint 228"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-233
test-233: check-232
	@echo "Running test 233..."
	./$(BINDIR)/test-233

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 236
OBJS_236 := $(OBJDIR)/file236_0.o $(OBJDIR)/file236_1.o $(OBJDIR)/file236_2.o $(OBJDIR)/file236_3.o 

$(OBJDIR)/file236_%.o: $(SRCDIR)/file236_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-237
docs-237:
	@echo "Running docs 237..."
	@echo "Done with docs 237"

.PHONY: lint-238
lint-238: clean-237
	@echo "Running lint 238..."
	@echo "Done with lint 238"

.PHONY: check-239
check-239: install-238
	@echo "Running check 239..."
	@echo "Done with check 239"

.PHONY: all-240
all-240:
	@echo "Running all 240..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-240 $(SRCDIR)/main-240.cpp $(LDFLAGS)

.PHONY: build-241
build-241: test-240
	@echo "Running build 241..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-241 $(SRCDIR)/main-241.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-243
test-243: dist-242
	@echo "Running test 243..."
	./$(BINDIR)/test-243

# Object files for module 244
OBJS_244 := $(OBJDIR)/file244_0.o $(OBJDIR)/file244_1.o $(OBJDIR)/file244_2.o $(OBJDIR)/file244_3.o 

$(OBJDIR)/file244_%.o: $(SRCDIR)/file244_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-245
run-245: test-244
	@echo "Running run 245..."
	@echo "Done with run 245"

# Object files for module 246
OBJS_246 := $(OBJDIR)/file246_0.o $(OBJDIR)/file246_1.o $(OBJDIR)/file246_2.o $(OBJDIR)/file246_3.o 

$(OBJDIR)/file246_%.o: $(SRCDIR)/file246_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-247
docs-247:
	@echo "Running docs 247..."
	@echo "Done with docs 247"

.PHONY: lint-248
lint-248: clean-247
	@echo "Running lint 248..."
	@echo "Done with lint 248"

.PHONY: check-249
check-249: lint-248
	@echo "Running check 249..."
	@echo "Done with check 249"

# Object files for module 250
OBJS_250 := $(OBJDIR)/file250_0.o $(OBJDIR)/file250_1.o $(OBJDIR)/file250_2.o $(OBJDIR)/file250_3.o $(OBJDIR)/file250_4.o $(OBJDIR)/file250_5.o 

$(OBJDIR)/file250_%.o: $(SRCDIR)/file250_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-253
test-253:
	@echo "Running test 253..."
	./$(BINDIR)/test-253

.PHONY: install-254
install-254: all-253
	@echo "Running install 254..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-254 $(SRCDIR)/main-254.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-260
all-260: clean-259
	@echo "Running all 260..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-260 $(SRCDIR)/main-260.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-262
clean-262: run-261
	@echo "Running clean 262..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-262

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 265
OBJS_265 := $(OBJDIR)/file265_0.o $(OBJDIR)/file265_1.o $(OBJDIR)/file265_2.o $(OBJDIR)/file265_3.o $(OBJDIR)/file265_4.o 

$(OBJDIR)/file265_%.o: $(SRCDIR)/file265_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 266
OBJS_266 := $(OBJDIR)/file266_0.o $(OBJDIR)/file266_1.o $(OBJDIR)/file266_2.o $(OBJDIR)/file266_3.o 

$(OBJDIR)/file266_%.o: $(SRCDIR)/file266_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 268
OBJS_268 := $(OBJDIR)/file268_0.o $(OBJDIR)/file268_1.o $(OBJDIR)/file268_2.o 

$(OBJDIR)/file268_%.o: $(SRCDIR)/file268_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 274
OBJS_274 := $(OBJDIR)/file274_0.o $(OBJDIR)/file274_1.o $(OBJDIR)/file274_2.o $(OBJDIR)/file274_3.o 

$(OBJDIR)/file274_%.o: $(SRCDIR)/file274_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-275
run-275:
	@echo "Running run 275..."
	@echo "Done with run 275"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-277
docs-277:
	@echo "Running docs 277..."
	@echo "Done with docs 277"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-279
check-279: check-278
	@echo "Running check 279..."
	@echo "Done with check 279"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 281
OBJS_281 := $(OBJDIR)/file281_0.o $(OBJDIR)/file281_1.o $(OBJDIR)/file281_2.o $(OBJDIR)/file281_3.o $(OBJDIR)/file281_4.o 

$(OBJDIR)/file281_%.o: $(SRCDIR)/file281_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: clean-282
clean-282:
	@echo "Running clean 282..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-282

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-284
install-284: dist-283
	@echo "Running install 284..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-284 $(SRCDIR)/main-284.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 287
OBJS_287 := $(OBJDIR)/file287_0.o $(OBJDIR)/file287_1.o $(OBJDIR)/file287_2.o 

$(OBJDIR)/file287_%.o: $(SRCDIR)/file287_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-289
check-289:
	@echo "Running check 289..."
	@echo "Done with check 289"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-291
build-291: test-290
	@echo "Running build 291..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-291 $(SRCDIR)/main-291.cpp $(LDFLAGS)

.PHONY: clean-292
clean-292:
	@echo "Running clean 292..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-292

# Object files for module 293
OBJS_293 := $(OBJDIR)/file293_0.o $(OBJDIR)/file293_1.o $(OBJDIR)/file293_2.o 

$(OBJDIR)/file293_%.o: $(SRCDIR)/file293_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: install-294
install-294:
	@echo "Running install 294..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-294 $(SRCDIR)/main-294.cpp $(LDFLAGS)

# Object files for module 295
OBJS_295 := $(OBJDIR)/file295_0.o $(OBJDIR)/file295_1.o $(OBJDIR)/file295_2.o $(OBJDIR)/file295_3.o $(OBJDIR)/file295_4.o 

$(OBJDIR)/file295_%.o: $(SRCDIR)/file295_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: dist-296
dist-296: dist-295
	@echo "Running dist 296..."
	@echo "Done with dist 296"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 299
OBJS_299 := $(OBJDIR)/file299_0.o $(OBJDIR)/file299_1.o $(OBJDIR)/file299_2.o $(OBJDIR)/file299_3.o $(OBJDIR)/file299_4.o 

$(OBJDIR)/file299_%.o: $(SRCDIR)/file299_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all-300
all-300: check-299
	@echo "Running all 300..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-300 $(SRCDIR)/main-300.cpp $(LDFLAGS)

.PHONY: build-301
build-301:
	@echo "Running build 301..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-301 $(SRCDIR)/main-301.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-303
test-303:
	@echo "Running test 303..."
	./$(BINDIR)/test-303

.PHONY: install-304
install-304: check-303
	@echo "Running install 304..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-304 $(SRCDIR)/main-304.cpp $(LDFLAGS)

.PHONY: run-305
run-305: check-304
	@echo "Running run 305..."
	@echo "Done with run 305"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-307
docs-307:
	@echo "Running docs 307..."
	@echo "Done with docs 307"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-312
clean-312:
	@echo "Running clean 312..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-312

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-316
dist-316:
	@echo "Running dist 316..."
	@echo "Done with dist 316"

# Object files for module 317
OBJS_317 := $(OBJDIR)/file317_0.o $(OBJDIR)/file317_1.o $(OBJDIR)/file317_2.o $(OBJDIR)/file317_3.o $(OBJDIR)/file317_4.o 

$(OBJDIR)/file317_%.o: $(SRCDIR)/file317_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 318
OBJS_318 := $(OBJDIR)/file318_0.o $(OBJDIR)/file318_1.o $(OBJDIR)/file318_2.o $(OBJDIR)/file318_3.o $(OBJDIR)/file318_4.o 

$(OBJDIR)/file318_%.o: $(SRCDIR)/file318_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-320
all-320:
	@echo "Running all 320..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-320 $(SRCDIR)/main-320.cpp $(LDFLAGS)

.PHONY: build-321
build-321: all-320
	@echo "Running build 321..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-321 $(SRCDIR)/main-321.cpp $(LDFLAGS)

# Object files for module 322
OBJS_322 := $(OBJDIR)/file322_0.o $(OBJDIR)/file322_1.o $(OBJDIR)/file322_2.o $(OBJDIR)/file322_3.o $(OBJDIR)/file322_4.o $(OBJDIR)/file322_5.o 

$(OBJDIR)/file322_%.o: $(SRCDIR)/file322_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-324
install-324:
	@echo "Running install 324..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-324 $(SRCDIR)/main-324.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-327
docs-327: lint-326
	@echo "Running docs 327..."
	@echo "Done with docs 327"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-330
all-330:
	@echo "Running all 330..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-330 $(SRCDIR)/main-330.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 332
OBJS_332 := $(OBJDIR)/file332_0.o $(OBJDIR)/file332_1.o $(OBJDIR)/file332_2.o $(OBJDIR)/file332_3.o $(OBJDIR)/file332_4.o $(OBJDIR)/file332_5.o 

$(OBJDIR)/file332_%.o: $(SRCDIR)/file332_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 333
OBJS_333 := $(OBJDIR)/file333_0.o $(OBJDIR)/file333_1.o $(OBJDIR)/file333_2.o $(OBJDIR)/file333_3.o $(OBJDIR)/file333_4.o 

$(OBJDIR)/file333_%.o: $(SRCDIR)/file333_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 334
OBJS_334 := $(OBJDIR)/file334_0.o $(OBJDIR)/file334_1.o $(OBJDIR)/file334_2.o $(OBJDIR)/file334_3.o 

$(OBJDIR)/file334_%.o: $(SRCDIR)/file334_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 339
OBJS_339 := $(OBJDIR)/file339_0.o $(OBJDIR)/file339_1.o $(OBJDIR)/file339_2.o $(OBJDIR)/file339_3.o $(OBJDIR)/file339_4.o 

$(OBJDIR)/file339_%.o: $(SRCDIR)/file339_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-342
clean-342: run-341
	@echo "Running clean 342..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-342

# Object files for module 343
OBJS_343 := $(OBJDIR)/file343_0.o $(OBJDIR)/file343_1.o $(OBJDIR)/file343_2.o 

$(OBJDIR)/file343_%.o: $(SRCDIR)/file343_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: install-344
install-344:
	@echo "Running install 344..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-344 $(SRCDIR)/main-344.cpp $(LDFLAGS)

.PHONY: run-345
run-345:
	@echo "Running run 345..."
	@echo "Done with run 345"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-347
docs-347:
	@echo "Running docs 347..."
	@echo "Done with docs 347"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-349
check-349:
	@echo "Running check 349..."
	@echo "Done with check 349"

# Object files for module 350
OBJS_350 := $(OBJDIR)/file350_0.o $(OBJDIR)/file350_1.o $(OBJDIR)/file350_2.o $(OBJDIR)/file350_3.o 

$(OBJDIR)/file350_%.o: $(SRCDIR)/file350_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 351
OBJS_351 := $(OBJDIR)/file351_0.o $(OBJDIR)/file351_1.o $(OBJDIR)/file351_2.o $(OBJDIR)/file351_3.o $(OBJDIR)/file351_4.o 

$(OBJDIR)/file351_%.o: $(SRCDIR)/file351_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 354
OBJS_354 := $(OBJDIR)/file354_0.o $(OBJDIR)/file354_1.o $(OBJDIR)/file354_2.o $(OBJDIR)/file354_3.o $(OBJDIR)/file354_4.o $(OBJDIR)/file354_5.o 

$(OBJDIR)/file354_%.o: $(SRCDIR)/file354_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 355
OBJS_355 := $(OBJDIR)/file355_0.o $(OBJDIR)/file355_1.o $(OBJDIR)/file355_2.o $(OBJDIR)/file355_3.o 

$(OBJDIR)/file355_%.o: $(SRCDIR)/file355_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-357
docs-357:
	@echo "Running docs 357..."
	@echo "Done with docs 357"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-360
all-360: install-359
	@echo "Running all 360..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-360 $(SRCDIR)/main-360.cpp $(LDFLAGS)

.PHONY: build-361
build-361:
	@echo "Running build 361..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-361 $(SRCDIR)/main-361.cpp $(LDFLAGS)

# Object files for module 362
OBJS_362 := $(OBJDIR)/file362_0.o $(OBJDIR)/file362_1.o $(OBJDIR)/file362_2.o $(OBJDIR)/file362_3.o 

$(OBJDIR)/file362_%.o: $(SRCDIR)/file362_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-363
test-363: check-362
	@echo "Running test 363..."
	./$(BINDIR)/test-363

.PHONY: install-364
install-364: clean-363
	@echo "Running install 364..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-364 $(SRCDIR)/main-364.cpp $(LDFLAGS)

.PHONY: run-365
run-365: run-364
	@echo "Running run 365..."
	@echo "Done with run 365"

# Object files for module 366
OBJS_366 := $(OBJDIR)/file366_0.o $(OBJDIR)/file366_1.o $(OBJDIR)/file366_2.o $(OBJDIR)/file366_3.o 

$(OBJDIR)/file366_%.o: $(SRCDIR)/file366_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-367
docs-367: clean-366
	@echo "Running docs 367..."
	@echo "Done with docs 367"

# Object files for module 368
OBJS_368 := $(OBJDIR)/file368_0.o $(OBJDIR)/file368_1.o $(OBJDIR)/file368_2.o $(OBJDIR)/file368_3.o 

$(OBJDIR)/file368_%.o: $(SRCDIR)/file368_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 370
OBJS_370 := $(OBJDIR)/file370_0.o $(OBJDIR)/file370_1.o $(OBJDIR)/file370_2.o 

$(OBJDIR)/file370_%.o: $(SRCDIR)/file370_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: build-371
build-371: all-370
	@echo "Running build 371..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-371 $(SRCDIR)/main-371.cpp $(LDFLAGS)

.PHONY: clean-372
clean-372: install-371
	@echo "Running clean 372..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-372

.PHONY: test-373
test-373: check-372
	@echo "Running test 373..."
	./$(BINDIR)/test-373

# Object files for module 374
OBJS_374 := $(OBJDIR)/file374_0.o $(OBJDIR)/file374_1.o $(OBJDIR)/file374_2.o 

$(OBJDIR)/file374_%.o: $(SRCDIR)/file374_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-375
run-375: docs-374
	@echo "Running run 375..."
	@echo "Done with run 375"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-377
docs-377:
	@echo "Running docs 377..."
	@echo "Done with docs 377"

.PHONY: lint-378
lint-378:
	@echo "Running lint 378..."
	@echo "Done with lint 378"

# Object files for module 379
OBJS_379 := $(OBJDIR)/file379_0.o $(OBJDIR)/file379_1.o $(OBJDIR)/file379_2.o $(OBJDIR)/file379_3.o $(OBJDIR)/file379_4.o 

$(OBJDIR)/file379_%.o: $(SRCDIR)/file379_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 381
OBJS_381 := $(OBJDIR)/file381_0.o $(OBJDIR)/file381_1.o $(OBJDIR)/file381_2.o 

$(OBJDIR)/file381_%.o: $(SRCDIR)/file381_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-384
install-384:
	@echo "Running install 384..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-384 $(SRCDIR)/main-384.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-386
dist-386:
	@echo "Running dist 386..."
	@echo "Done with dist 386"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 388
OBJS_388 := $(OBJDIR)/file388_0.o $(OBJDIR)/file388_1.o $(OBJDIR)/file388_2.o 

$(OBJDIR)/file388_%.o: $(SRCDIR)/file388_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 389
OBJS_389 := $(OBJDIR)/file389_0.o $(OBJDIR)/file389_1.o $(OBJDIR)/file389_2.o $(OBJDIR)/file389_3.o $(OBJDIR)/file389_4.o $(OBJDIR)/file389_5.o 

$(OBJDIR)/file389_%.o: $(SRCDIR)/file389_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 390
OBJS_390 := $(OBJDIR)/file390_0.o $(OBJDIR)/file390_1.o $(OBJDIR)/file390_2.o 

$(OBJDIR)/file390_%.o: $(SRCDIR)/file390_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 392
OBJS_392 := $(OBJDIR)/file392_0.o $(OBJDIR)/file392_1.o $(OBJDIR)/file392_2.o $(OBJDIR)/file392_3.o 

$(OBJDIR)/file392_%.o: $(SRCDIR)/file392_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-397
docs-397:
	@echo "Running docs 397..."
	@echo "Done with docs 397"

.PHONY: lint-398
lint-398: test-397
	@echo "Running lint 398..."
	@echo "Done with lint 398"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 402
OBJS_402 := $(OBJDIR)/file402_0.o $(OBJDIR)/file402_1.o $(OBJDIR)/file402_2.o $(OBJDIR)/file402_3.o 

$(OBJDIR)/file402_%.o: $(SRCDIR)/file402_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-403
test-403: run-402
	@echo "Running test 403..."
	./$(BINDIR)/test-403

.PHONY: install-404
install-404: dist-403
	@echo "Running install 404..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-404 $(SRCDIR)/main-404.cpp $(LDFLAGS)

# Object files for module 405
OBJS_405 := $(OBJDIR)/file405_0.o $(OBJDIR)/file405_1.o $(OBJDIR)/file405_2.o $(OBJDIR)/file405_3.o $(OBJDIR)/file405_4.o $(OBJDIR)/file405_5.o $(OBJDIR)/file405_6.o 

$(OBJDIR)/file405_%.o: $(SRCDIR)/file405_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-407
docs-407:
	@echo "Running docs 407..."
	@echo "Done with docs 407"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-412
clean-412:
	@echo "Running clean 412..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-412

.PHONY: test-413
test-413: test-412
	@echo "Running test 413..."
	./$(BINDIR)/test-413

# Object files for module 414
OBJS_414 := $(OBJDIR)/file414_0.o $(OBJDIR)/file414_1.o $(OBJDIR)/file414_2.o $(OBJDIR)/file414_3.o $(OBJDIR)/file414_4.o $(OBJDIR)/file414_5.o 

$(OBJDIR)/file414_%.o: $(SRCDIR)/file414_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: run-415
run-415: run-414
	@echo "Running run 415..."
	@echo "Done with run 415"

# Object files for module 416
OBJS_416 := $(OBJDIR)/file416_0.o $(OBJDIR)/file416_1.o $(OBJDIR)/file416_2.o 

$(OBJDIR)/file416_%.o: $(SRCDIR)/file416_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 419
OBJS_419 := $(OBJDIR)/file419_0.o $(OBJDIR)/file419_1.o $(OBJDIR)/file419_2.o $(OBJDIR)/file419_3.o $(OBJDIR)/file419_4.o $(OBJDIR)/file419_5.o 

$(OBJDIR)/file419_%.o: $(SRCDIR)/file419_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 421
OBJS_421 := $(OBJDIR)/file421_0.o $(OBJDIR)/file421_1.o $(OBJDIR)/file421_2.o $(OBJDIR)/file421_3.o $(OBJDIR)/file421_4.o $(OBJDIR)/file421_5.o 

$(OBJDIR)/file421_%.o: $(SRCDIR)/file421_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: test-423
test-423: test-422
	@echo "Running test 423..."
	./$(BINDIR)/test-423

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 425
OBJS_425 := $(OBJDIR)/file425_0.o $(OBJDIR)/file425_1.o $(OBJDIR)/file425_2.o $(OBJDIR)/file425_3.o 

$(OBJDIR)/file425_%.o: $(SRCDIR)/file425_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 426
OBJS_426 := $(OBJDIR)/file426_0.o $(OBJDIR)/file426_1.o $(OBJDIR)/file426_2.o $(OBJDIR)/file426_3.o $(OBJDIR)/file426_4.o $(OBJDIR)/file426_5.o 

$(OBJDIR)/file426_%.o: $(SRCDIR)/file426_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-429
check-429:
	@echo "Running check 429..."
	@echo "Done with check 429"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-431
build-431: build-430
	@echo "Running build 431..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-431 $(SRCDIR)/main-431.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-434
install-434: lint-433
	@echo "Running install 434..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-434 $(SRCDIR)/main-434.cpp $(LDFLAGS)

.PHONY: run-435
run-435: all-434
	@echo "Running run 435..."
	@echo "Done with run 435"

.PHONY: dist-436
dist-436:
	@echo "Running dist 436..."
	@echo "Done with dist 436"

.PHONY: docs-437
docs-437: all-436
	@echo "Running docs 437..."
	@echo "Done with docs 437"

.PHONY: lint-438
lint-438:
	@echo "Running lint 438..."
	@echo "Done with lint 438"

# Object files for module 439
OBJS_439 := $(OBJDIR)/file439_0.o $(OBJDIR)/file439_1.o $(OBJDIR)/file439_2.o $(OBJDIR)/file439_3.o 

$(OBJDIR)/file439_%.o: $(SRCDIR)/file439_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-441
build-441:
	@echo "Running build 441..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-441 $(SRCDIR)/main-441.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-444
install-444:
	@echo "Running install 444..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-444 $(SRCDIR)/main-444.cpp $(LDFLAGS)

# Object files for module 445
OBJS_445 := $(OBJDIR)/file445_0.o $(OBJDIR)/file445_1.o $(OBJDIR)/file445_2.o 

$(OBJDIR)/file445_%.o: $(SRCDIR)/file445_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 446
OBJS_446 := $(OBJDIR)/file446_0.o $(OBJDIR)/file446_1.o $(OBJDIR)/file446_2.o 

$(OBJDIR)/file446_%.o: $(SRCDIR)/file446_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-449
check-449:
	@echo "Running check 449..."
	@echo "Done with check 449"

.PHONY: all-450
all-450:
	@echo "Running all 450..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-450 $(SRCDIR)/main-450.cpp $(LDFLAGS)

.PHONY: build-451
build-451: install-450
	@echo "Running build 451..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-451 $(SRCDIR)/main-451.cpp $(LDFLAGS)

# Object files for module 452
OBJS_452 := $(OBJDIR)/file452_0.o $(OBJDIR)/file452_1.o $(OBJDIR)/file452_2.o $(OBJDIR)/file452_3.o 

$(OBJDIR)/file452_%.o: $(SRCDIR)/file452_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 454
OBJS_454 := $(OBJDIR)/file454_0.o $(OBJDIR)/file454_1.o $(OBJDIR)/file454_2.o 

$(OBJDIR)/file454_%.o: $(SRCDIR)/file454_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-457
docs-457: check-456
	@echo "Running docs 457..."
	@echo "Done with docs 457"

.PHONY: lint-458
lint-458: test-457
	@echo "Running lint 458..."
	@echo "Done with lint 458"

# Object files for module 459
OBJS_459 := $(OBJDIR)/file459_0.o $(OBJDIR)/file459_1.o $(OBJDIR)/file459_2.o $(OBJDIR)/file459_3.o $(OBJDIR)/file459_4.o 

$(OBJDIR)/file459_%.o: $(SRCDIR)/file459_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all-460
all-460: all-459
	@echo "Running all 460..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-460 $(SRCDIR)/main-460.cpp $(LDFLAGS)

.PHONY: build-461
build-461:
	@echo "Running build 461..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-461 $(SRCDIR)/main-461.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-466
dist-466: lint-465
	@echo "Running dist 466..."
	@echo "Done with dist 466"

.PHONY: docs-467
docs-467: docs-466
	@echo "Running docs 467..."
	@echo "Done with docs 467"

.PHONY: lint-468
lint-468:
	@echo "Running lint 468..."
	@echo "Done with lint 468"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 471
OBJS_471 := $(OBJDIR)/file471_0.o $(OBJDIR)/file471_1.o $(OBJDIR)/file471_2.o $(OBJDIR)/file471_3.o $(OBJDIR)/file471_4.o 

$(OBJDIR)/file471_%.o: $(SRCDIR)/file471_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: install-474
install-474: run-473
	@echo "Running install 474..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-474 $(SRCDIR)/main-474.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-476
dist-476:
	@echo "Running dist 476..."
	@echo "Done with dist 476"

.PHONY: docs-477
docs-477: all-476
	@echo "Running docs 477..."
	@echo "Done with docs 477"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 480
OBJS_480 := $(OBJDIR)/file480_0.o $(OBJDIR)/file480_1.o $(OBJDIR)/file480_2.o 

$(OBJDIR)/file480_%.o: $(SRCDIR)/file480_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 481
OBJS_481 := $(OBJDIR)/file481_0.o $(OBJDIR)/file481_1.o $(OBJDIR)/file481_2.o $(OBJDIR)/file481_3.o 

$(OBJDIR)/file481_%.o: $(SRCDIR)/file481_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 483
OBJS_483 := $(OBJDIR)/file483_0.o $(OBJDIR)/file483_1.o $(OBJDIR)/file483_2.o $(OBJDIR)/file483_3.o $(OBJDIR)/file483_4.o 

$(OBJDIR)/file483_%.o: $(SRCDIR)/file483_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 484
OBJS_484 := $(OBJDIR)/file484_0.o $(OBJDIR)/file484_1.o $(OBJDIR)/file484_2.o $(OBJDIR)/file484_3.o $(OBJDIR)/file484_4.o 

$(OBJDIR)/file484_%.o: $(SRCDIR)/file484_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 485
OBJS_485 := $(OBJDIR)/file485_0.o $(OBJDIR)/file485_1.o $(OBJDIR)/file485_2.o $(OBJDIR)/file485_3.o 

$(OBJDIR)/file485_%.o: $(SRCDIR)/file485_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: dist-486
dist-486:
	@echo "Running dist 486..."
	@echo "Done with dist 486"

# Object files for module 487
OBJS_487 := $(OBJDIR)/file487_0.o $(OBJDIR)/file487_1.o $(OBJDIR)/file487_2.o $(OBJDIR)/file487_3.o $(OBJDIR)/file487_4.o $(OBJDIR)/file487_5.o 

$(OBJDIR)/file487_%.o: $(SRCDIR)/file487_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 489
OBJS_489 := $(OBJDIR)/file489_0.o $(OBJDIR)/file489_1.o $(OBJDIR)/file489_2.o 

$(OBJDIR)/file489_%.o: $(SRCDIR)/file489_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 492
OBJS_492 := $(OBJDIR)/file492_0.o $(OBJDIR)/file492_1.o $(OBJDIR)/file492_2.o $(OBJDIR)/file492_3.o $(OBJDIR)/file492_4.o 

$(OBJDIR)/file492_%.o: $(SRCDIR)/file492_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-495
run-495: lint-494
	@echo "Running run 495..."
	@echo "Done with run 495"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 497
OBJS_497 := $(OBJDIR)/file497_0.o $(OBJDIR)/file497_1.o $(OBJDIR)/file497_2.o $(OBJDIR)/file497_3.o $(OBJDIR)/file497_4.o 

$(OBJDIR)/file497_%.o: $(SRCDIR)/file497_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: check-499
check-499:
	@echo "Running check 499..."
	@echo "Done with check 499"

.PHONY: all-500
all-500:
	@echo "Running all 500..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-500 $(SRCDIR)/main-500.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 504
OBJS_504 := $(OBJDIR)/file504_0.o $(OBJDIR)/file504_1.o $(OBJDIR)/file504_2.o $(OBJDIR)/file504_3.o $(OBJDIR)/file504_4.o $(OBJDIR)/file504_5.o 

$(OBJDIR)/file504_%.o: $(SRCDIR)/file504_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Object files for module 505
OBJS_505 := $(OBJDIR)/file505_0.o $(OBJDIR)/file505_1.o $(OBJDIR)/file505_2.o $(OBJDIR)/file505_3.o $(OBJDIR)/file505_4.o $(OBJDIR)/file505_5.o 

$(OBJDIR)/file505_%.o: $(SRCDIR)/file505_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: lint-508
lint-508: all-507
	@echo "Running lint 508..."
	@echo "Done with lint 508"

.PHONY: check-509
check-509:
	@echo "Running check 509..."
	@echo "Done with check 509"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-511
build-511:
	@echo "Running build 511..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-511 $(SRCDIR)/main-511.cpp $(LDFLAGS)

.PHONY: clean-512
clean-512:
	@echo "Running clean 512..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-512

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 514
OBJS_514 := $(OBJDIR)/file514_0.o $(OBJDIR)/file514_1.o $(OBJDIR)/file514_2.o $(OBJDIR)/file514_3.o 

$(OBJDIR)/file514_%.o: $(SRCDIR)/file514_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 516
OBJS_516 := $(OBJDIR)/file516_0.o $(OBJDIR)/file516_1.o $(OBJDIR)/file516_2.o $(OBJDIR)/file516_3.o 

$(OBJDIR)/file516_%.o: $(SRCDIR)/file516_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-517
docs-517:
	@echo "Running docs 517..."
	@echo "Done with docs 517"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-522
clean-522:
	@echo "Running clean 522..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-522

.PHONY: test-523
test-523: install-522
	@echo "Running test 523..."
	./$(BINDIR)/test-523

# Object files for module 524
OBJS_524 := $(OBJDIR)/file524_0.o $(OBJDIR)/file524_1.o $(OBJDIR)/file524_2.o $(OBJDIR)/file524_3.o $(OBJDIR)/file524_4.o 

$(OBJDIR)/file524_%.o: $(SRCDIR)/file524_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: dist-526
dist-526: install-525
	@echo "Running dist 526..."
	@echo "Done with dist 526"

.PHONY: docs-527
docs-527:
	@echo "Running docs 527..."
	@echo "Done with docs 527"

.PHONY: lint-528
lint-528: build-527
	@echo "Running lint 528..."
	@echo "Done with lint 528"

.PHONY: check-529
check-529:
	@echo "Running check 529..."
	@echo "Done with check 529"

# Object files for module 530
OBJS_530 := $(OBJDIR)/file530_0.o $(OBJDIR)/file530_1.o $(OBJDIR)/file530_2.o $(OBJDIR)/file530_3.o 

$(OBJDIR)/file530_%.o: $(SRCDIR)/file530_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 532
OBJS_532 := $(OBJDIR)/file532_0.o $(OBJDIR)/file532_1.o $(OBJDIR)/file532_2.o $(OBJDIR)/file532_3.o 

$(OBJDIR)/file532_%.o: $(SRCDIR)/file532_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: test-533
test-533:
	@echo "Running test 533..."
	./$(BINDIR)/test-533

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-535
run-535:
	@echo "Running run 535..."
	@echo "Done with run 535"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: lint-538
lint-538: docs-537
	@echo "Running lint 538..."
	@echo "Done with lint 538"

# Object files for module 539
OBJS_539 := $(OBJDIR)/file539_0.o $(OBJDIR)/file539_1.o $(OBJDIR)/file539_2.o $(OBJDIR)/file539_3.o $(OBJDIR)/file539_4.o $(OBJDIR)/file539_5.o 

$(OBJDIR)/file539_%.o: $(SRCDIR)/file539_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-541
build-541: build-540
	@echo "Running build 541..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-541 $(SRCDIR)/main-541.cpp $(LDFLAGS)

.PHONY: clean-542
clean-542:
	@echo "Running clean 542..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-542

.PHONY: test-543
test-543:
	@echo "Running test 543..."
	./$(BINDIR)/test-543

.PHONY: install-544
install-544:
	@echo "Running install 544..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-544 $(SRCDIR)/main-544.cpp $(LDFLAGS)

.PHONY: run-545
run-545:
	@echo "Running run 545..."
	@echo "Done with run 545"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-547
docs-547:
	@echo "Running docs 547..."
	@echo "Done with docs 547"

# Object files for module 548
OBJS_548 := $(OBJDIR)/file548_0.o $(OBJDIR)/file548_1.o $(OBJDIR)/file548_2.o 

$(OBJDIR)/file548_%.o: $(SRCDIR)/file548_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: check-549
check-549: lint-548
	@echo "Running check 549..."
	@echo "Done with check 549"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: build-551
build-551: check-550
	@echo "Running build 551..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-551 $(SRCDIR)/main-551.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

# Object files for module 553
OBJS_553 := $(OBJDIR)/file553_0.o $(OBJDIR)/file553_1.o $(OBJDIR)/file553_2.o $(OBJDIR)/file553_3.o 

$(OBJDIR)/file553_%.o: $(SRCDIR)/file553_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: install-554
install-554:
	@echo "Running install 554..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-554 $(SRCDIR)/main-554.cpp $(LDFLAGS)

.PHONY: run-555
run-555:
	@echo "Running run 555..."
	@echo "Done with run 555"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: docs-557
docs-557:
	@echo "Running docs 557..."
	@echo "Done with docs 557"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: all-560
all-560: lint-559
	@echo "Running all 560..."
	$(CXX) $(CXXFLAGS) -o $(BINDIR)/app-560 $(SRCDIR)/main-560.cpp $(LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-562
clean-562:
	@echo "Running clean 562..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-562

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: run-565
run-565: test-564
	@echo "Running run 565..."
	@echo "Done with run 565"

# Object files for module 566
OBJS_566 := $(OBJDIR)/file566_0.o $(OBJDIR)/file566_1.o $(OBJDIR)/file566_2.o $(OBJDIR)/file566_3.o $(OBJDIR)/file566_4.o 

$(OBJDIR)/file566_%.o: $(SRCDIR)/file566_%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: docs-567
docs-567: lint-566
	@echo "Running docs 567..."
	@echo "Done with docs 567"

.PHONY: lint-568
lint-568:
	@echo "Running lint 568..."
	@echo "Done with lint 568"

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -DDEBUG
CXXFLAGS += -g -DDEBUG
endif

.PHONY: clean-572
clean-572: install-571
	@echo "Running clean 572..."
	rm -rf $(OBJDIR)/*.o $(BINDIR)/app-572

# Object files for module 573
OBJS_573 := $(OBJDIR)/file573_0.o $(OBJDIR)/file573_1.o $(OBJDIR)/file573_2.o $(OBJDIR)/file573_3.o 

$(OBJDIR)/file573_%.o: $(SRCDIR)/file573_%.cpp
	$