#!/usr/bin/env python3
"""Does the Hub's GGUF population carry what a store would need to regenerate it?

RESULT 59 showed all seven of one publisher's quant types reproduce bit-exactly from the base under a
four-item recipe. 0.141 PB of the week's uploads rides on whether that generalises, and it has never been
sized. Regenerating a sample outright costs a multi-GB download and minutes of quantizer time per file,
so this measures the two things that bound the lever and cost only range requests:

  1 PROVENANCE. llama.cpp writes its recipe into the GGUF's own KV metadata. Reading the header alone
    (a few hundred KB) gives the quant type, the quantization version, whether an imatrix was used and
    which dataset it came from, and on newer files the base model repo and revision. A file with no
    provenance cannot be regenerated by anyone, so this is the ceiling of the lever.
  2 THE REPO'S OWN ARITHMETIC. A quant repo publishes N quantisations of ONE model. If the F16 or BF16
    GGUF is in the repo, then storing that one file plus N recipes replaces every quant. The reduction
    factor is (sum of all GGUF bytes) / (the F16's bytes), and it needs no download at all.

Both are read from the sampled population, so the answer is weighted the way the Hub actually is."""
import json, os, re, struct, subprocess, time
H = "https://huggingface.co"; B = "/root/mzip-hfbench"; OUT = f"{B}/gguf-prov"
os.makedirs(OUT, exist_ok=True)
HDR = 24 * 1024 * 1024

def sh(a, t=200): return subprocess.run(a, capture_output=True, text=True, timeout=t)
def api(u):
    try: return json.loads(sh(["curl", "-sS", "-g", "--max-time", "90", u]).stdout)
    except Exception: return None

def read_kv(repo, path):
    """parse GGUF KV metadata from the first MiB; returns {key: value} for the keys we care about"""
    tmp = f"{OUT}/h.tmp"
    sh(["curl", "-sSL", "--max-time", "120", "-r", f"0-{HDR-1}", "-o", tmp,
        f"{H}/{repo}/resolve/main/{path}"], t=150)
    try: b = open(tmp, "rb").read()
    except Exception: return None
    if len(b) < 24 or b[:4] != b"GGUF": return None
    ver = struct.unpack("<I", b[4:8])[0]
    if ver not in (2, 3): return None
    n_tensor, n_kv = struct.unpack("<QQ", b[8:24])
    p = 24; out = {}
    def rd_str():
        nonlocal p
        (ln,) = struct.unpack("<Q", b[p:p+8]); p += 8
        s = b[p:p+ln]; p += ln
        return s.decode("utf-8", "replace")
    T = {0:1,1:1,2:2,3:2,4:4,5:4,6:4,7:1,10:8,11:8,12:8}
    def skip_val(t):
        nonlocal p
        if t == 8: rd_str(); return
        if t == 9:
            (et,) = struct.unpack("<I", b[p:p+4]); p += 4
            (cnt,) = struct.unpack("<Q", b[p:p+8]); p += 8
            for _ in range(cnt):
                if et == 8: rd_str()
                elif et == 9: return
                else: p += T.get(et, 4)
            return
        p += T.get(t, 4)
    def read_val(t):
        nonlocal p
        if t == 8: return rd_str()
        if t in (4, 5): v = struct.unpack("<i" if t == 5 else "<I", b[p:p+4])[0]; p += 4; return v
        if t in (10, 11): v = struct.unpack("<q" if t == 11 else "<Q", b[p:p+8])[0]; p += 8; return v
        if t == 6: v = struct.unpack("<f", b[p:p+4])[0]; p += 4; return v
        if t == 7: v = b[p]; p += 1; return bool(v)
        skip_val(t); return None
    try:
        for _ in range(min(n_kv, 4096)):
            k = rd_str()
            (t,) = struct.unpack("<I", b[p:p+4]); p += 4
            if k.startswith(("quantize.", "general.file_type", "general.quantization_version",
                             "general.base_model", "general.name", "general.basename",
                             "general.size_label", "general.finetune", "general.type")):
                out[k] = read_val(t)
            else: skip_val(t)
            if p > len(b) - 16: break
    except Exception: pass
    out["_tensors"] = n_tensor
    return out

def main():
    rows = [json.loads(l) for l in open(f"{B}/upload-mix/sample_models.jsonl")]
    rows = [r for r in rows if r.get("ok") and any(k.startswith("gguf") for k in r.get("bytes_in_window", {}))]
    rows.sort(key=lambda r: -sum(v for k, v in r["bytes_in_window"].items() if k.startswith("gguf")))
    print(f"{len(rows)} sampled repos hold GGUF bytes; taking the heaviest 60\n")
    print(f"{'repo':44s} {'gguf files':>10s} {'gguf bytes':>11s} {'F16 in repo':>12s} {'factor':>7s} {'imatrix':>8s} {'base named':>11s}")
    tot_g = tot_f = 0.0; withf16 = 0; n = 0; prov = {"imatrix": 0, "base": 0, "quantver": 0, "none": 0}
    recs = []
    for r in rows[:35]:
        t = api(f"{H}/api/models/{r['id']}/tree/main?recursive=true&limit=1000")
        if not isinstance(t, list): continue
        gg = [(f["path"], int(f.get("size") or 0)) for f in t
              if f.get("type") == "file" and f["path"].lower().endswith(".gguf")]
        if not gg: continue
        gbytes = sum(s for _, s in gg)
        f16 = [(p, s) for p, s in gg if re.search(r"(?i)(^|[-_.])(f16|fp16|bf16|f32)([-_.]|$)", p.rsplit("/", 1)[-1])]
        base_sz = max((s for _, s in f16), default=0)
        st = [int(f.get("size") or 0) for f in t if f.get("type") == "file" and f["path"].endswith(".safetensors")]
        if not base_sz and st: base_sz = sum(st)
        factor = gbytes / base_sz if base_sz else 0
        # provenance from the largest quant that is not the f16 itself
        q = sorted([(s, p) for p, s in gg if (p, s) not in f16], reverse=True)
        kv = read_kv(r["id"], q[0][1]) if q else None
        im = bool(kv and any(k.startswith("quantize.imatrix") for k in kv)) if kv else False
        bm = bool(kv and any(k.startswith("general.base_model") for k in kv)) if kv else False
        qv = bool(kv and "general.quantization_version" in kv) if kv else False
        if kv:
            if im: prov["imatrix"] += 1
            if bm: prov["base"] += 1
            if qv: prov["quantver"] += 1
            if not (im or bm or qv): prov["none"] += 1
        tot_g += gbytes; tot_f += base_sz; withf16 += bool(base_sz); n += 1
        recs.append(dict(repo=r["id"], files=len(gg), gbytes=gbytes, base=base_sz, factor=factor,
                         imatrix=im, base_named=bm, quantver=qv, kv={k: v for k, v in (kv or {}).items() if not k.startswith("_")}))
        print(f"{r['id'][:44]:44s} {len(gg):10d} {gbytes/1e9:10.1f}G {(base_sz/1e9 if base_sz else 0):11.1f}G "
              f"{factor:7.2f} {('yes' if im else '-'):>8s} {('yes' if bm else '-'):>11s}", flush=True)
        json.dump(recs, open(f"{OUT}/gguf_prov.json", "w"), indent=1, default=str)
        time.sleep(0.1)
    print()
    print(f"repos with GGUF: {n} | with an F16/BF16 or safetensors base IN THE SAME REPO: {withf16} ({100*withf16/max(n,1):.0f}%)")
    print(f"total GGUF bytes {tot_g/1e12:.2f} TB across those repos; their in-repo bases {tot_f/1e12:.2f} TB")
    if tot_f: print(f"  => storing the base plus recipes instead of the quants: {tot_g/tot_f:.2f}x fewer bytes")
    print(f"provenance in the largest quant of each repo: imatrix named {prov['imatrix']}, "
          f"base model named {prov['base']}, quantization_version {prov['quantver']}, none of the three {prov['none']}")
    print("GGUF_PROV_DONE")

if __name__ == "__main__":
    main()
